//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagements.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventManagementSystemEntities : DbContext
    {
        public EventManagementSystemEntities()
            : base("name=EventManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<Tablebookvenue> Tablebookvenues { get; set; }
        public virtual DbSet<Tableevent> Tableevents { get; set; }
        public virtual DbSet<Tableservice> Tableservices { get; set; }
        public virtual DbSet<Tablevenue> Tablevenues { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
    }
}
