//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagements.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablebookvenue
    {
        public int id { get; set; }
        public string name { get; set; }
        public string mobilenumber { get; set; }
        public string event1 { get; set; }
        public string venue { get; set; }
        public Nullable<System.DateTime> eventdate { get; set; }
        public string requirements { get; set; }
    }
}
