//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagements.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablevenue
    {
        public int venueid { get; set; }
        public string venue { get; set; }
        public string events1 { get; set; }
    }
}
