//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagements.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tableservice
    {
        public int serviceid { get; set; }
        public string servicename { get; set; }
        public Nullable<decimal> servicecharge { get; set; }
    }
}
